inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - bin/**/*

  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '**/*.rake'
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'
Style/Documentation:
  Exclude:
    - 'app/**/*.rb'

GlobalVars:
  AllowedVariables:
    - $redis_rider
    - $redis_lock
    - $redis_live
ClassLength:
  Max: 700
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 140
